# Idempotent: safe to run more than once (`bin/rails db:seed`).

GAMES = [
  "The Legend of Zelda: Breath of the Wild",
  "The Legend of Zelda: Ocarina of Time",
  "The Legend of Zelda: Tears of the Kingdom",
  "Super Mario Bros.",
  "Super Mario 64",
  "Super Mario Odyssey",
  "Mario Kart 8 Deluxe",
  "Super Smash Bros. Ultimate",
  "Metroid Prime",
  "Pokémon Red and Blue",
  "Pokémon Gold and Silver",
  "Animal Crossing: New Horizons",
  "Tetris",
  "Pac-Man",
  "Sonic the Hedgehog",
  "Street Fighter II",
  "Final Fantasy VII",
  "Final Fantasy X",
  "Chrono Trigger",
  "Persona 5 Royal",
  "Metal Gear Solid",
  "Resident Evil 4",
  "Resident Evil 2",
  "Silent Hill 2",
  "Devil May Cry 5",
  "Monster Hunter: World",
  "Dark Souls",
  "Bloodborne",
  "Sekiro: Shadows Die Twice",
  "Elden Ring",
  "The Witcher 3: Wild Hunt",
  "Cyberpunk 2077",
  "Baldur's Gate 3",
  "Divinity: Original Sin 2",
  "The Elder Scrolls V: Skyrim",
  "The Elder Scrolls III: Morrowind",
  "Fallout 3",
  "Fallout: New Vegas",
  "Mass Effect 2",
  "Dragon Age: Origins",
  "Diablo II",
  "World of Warcraft",
  "StarCraft",
  "Half-Life",
  "Half-Life 2",
  "Portal",
  "Portal 2",
  "Counter-Strike: Global Offensive",
  "Team Fortress 2",
  "Left 4 Dead 2",
  "DOOM (2016)",
  "DOOM Eternal",
  "Quake",
  "Halo: Combat Evolved",
  "Halo 3",
  "Call of Duty 4: Modern Warfare",
  "Overwatch",
  "Fortnite",
  "Grand Theft Auto III",
  "Grand Theft Auto: San Andreas",
  "Grand Theft Auto V",
  "Red Dead Redemption 2",
  "Red Dead Redemption",
  "The Last of Us",
  "The Last of Us Part II",
  "Uncharted 2: Among Thieves",
  "God of War (2018)",
  "God of War Ragnarök",
  "Horizon Zero Dawn",
  "Ghost of Tsushima",
  "Marvel's Spider-Man",
  "Assassin's Creed II",
  "Batman: Arkham City",
  "BioShock",
  "BioShock Infinite",
  "Minecraft",
  "Terraria",
  "Stardew Valley",
  "Hollow Knight",
  "Celeste",
  "Hades",
  "Undertale",
  "Cuphead",
  "Ori and the Blind Forest",
  "Disco Elysium",
  "Civilization VI",
  "Age of Empires II",
  "The Sims 3",
  "XCOM: Enemy Unknown",
  "Rocket League",
  "League of Legends",
  "Dota 2",
  "Among Us",
  "Death Stranding",
  "Control",
  "Outer Wilds",
  "Return of the Obra Dinn",
  "Slay the Spire",
  "Vampire Survivors",
  "Starfield"
].freeze

created = GAMES.count { |name| Game.find_or_create_by!(name: name).previously_new_record? }
puts "Games seeded: #{created} created, #{GAMES.size - created} already present (#{Game.count} total)"
